# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/WebApplication/WebApplication1/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'feynmanfan-github'
    scannerMode: 'MSBuild'
    projectKey: 'WebApplication1'
    projectName: 'WebApplication1'
    extraProperties: |
      sonar.exclusions=**/*.bin
      sonar.cs.dotcover.reportsPaths=$(Common.TestResultsDirectory)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'WebApplication\CodeQUality.BusinessObjects.tests\CodeQUality.BusinessObjects.Tests.csproj'
    arguments: '--logger:"trx;LogFileName=$(Common.TestResultsDirectory)" --collect:"Code Coverage" /p:CoverletOutputFormat=opencover'

- task: SonarCloudAnalyze@1